### getToken(login)
POST http://localhost:9090/user/login
Content-Type: application/json

{
  "username": "ddi1",
  "password": "157e4fc9cead4d44332b98f72cdc37ce2707e7e3"
}

> {% client.global.set("auth_token", response.body.json.data.token); %}

### getUserInfo
GET http://localhost:9090/user/info
Authorization: Bearer {{auth_token}}

###