name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Build Failed'
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'Build Succeed'

      - uses: actions/download-artifact@v3
        with:
          name: jar-package

      - run: ls -R