name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Container
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/ceea
            git clone https://ghproxy.com/https://github.com/AkagiYui/ceea-backend.git build
            cd build
            mvn -B install --file pom.xml
            docker build -f Dockerfile.deploy -t ceea-backend .
            cd ..
            rm -rf build
            docker container rm -f ceea-backend
            docker run -d --name ceea-backend --restart=on-failure:3 -v /home/ceea/data:/data -p 9090:9090 ceea-backend
            docker image prune -f
            docker volume prune -f
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY}}